spring:
  application:
    name: analysis
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/analysis
    username: user
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/analysis
    user: user
    password: password

