spring:
  jmx:
    enabled: false
  application:
    name: analysis
  r2dbc:
    url: ${DB_REACT_URL:r2dbc:postgresql://localhost:5432/analysis}
    username: user
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${DB_URL:jdbc:postgresql://localhost:5432/analysis}
    user: user
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB
auth:
  issuer: clear-breath
  secret: ${AUTH_SECRET}

logging:
  level:
    root: INFO
    ua.com.goit.clearbreath: DEBUG


